cd /home/pi/Desktop
rm /home/pi/Desktop/adf435*
cd /home/pi/Desktop/10k
rm /home/pi/Desktop/10k/adf435*
cd /home/pi/Desktop
rmdir 10k
cd testmodules
rm /home/pi/Desktop/testmodules/*
cd /home/pi/Desktop
rmdir testmodules
rm install
rm 10k.sh
rm alloffrd.sh
rm fixpermissions.sh
rm loadrd.sh
rm loadrd2.sh
rm ramdisk.sh
rm RAND.sh
rm sa.sh
rm sa2.sh
rm sa3.sh
rm startall.sh
rm startall2.sh
rm startall3.sh
rm startall6.sh
rm startDLPFC.sh
rm startDLPFC2.sh
rm startPTSD.sh
rm startPTSD2.sh
rm Keyboardinstall.txt
rm newstart.txt
cd startall2
rm /home/pi/Desktop/startall2/*
cd /home/pi/Desktop
cd startall3
rm /home/pi/Desktop/startall3*
cd /home/pi/Desktop
rmdir startall2
rmdir startall3
cd I3
rm /home/pi/Desktop/I3/*
cd /home/pi/Desktop
rmdir I3
